# Generated by Django 4.2.16 on 2024-10-31 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exercise_category_photos/')),
            ],
            options={
                'verbose_name': 'Exercise Category',
                'verbose_name_plural': 'Exercise Categories',
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exercise_type_photos/')),
            ],
            options={
                'verbose_name': 'Exercise Type',
                'verbose_name_plural': 'Exercise Types',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exercise_photos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Новичок'), ('intermediate', 'Средний уровень'), ('advanced', 'Продвинутый')], default='beginner', max_length=50)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exercises.exercisecategory')),
                ('exercise_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exercises.exercisetype')),
            ],
        ),
    ]
