# Generated by Django 4.2.16 on 2024-10-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
